/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uagrm.ficct.ed1.proyecto1.ui.forms;

import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import edu.uagrm.ficct.ed1.proyecto1.ui.views.*;
import edu.uagrm.ficct.ed1.proyecto1.utils.graphicUtils;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JPanel;

/**
 * Formulario principal del programa.
 *
 * @author OJavierHR
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Variable donde de inicializan y se guardan las vistas que tendra el
     * programa.
     */
    private static HashMap<String, JPanel> listViews;
    private static boolean modeDark;

    /**
     * Constructor del formulario principal.
     */
    public FormMain() {
        initComponents();
        initStyles();
        initViews();
    }

    /**
     * Funcion en el que se inicia los estilos de componentes del UI. Son
     * recomendaciones de implementacion para el uso de la libreria flatlaf
     */
    private void initStyles() {
        graphicUtils.setStyle(titleLabel, null,
                Color.black);
        graphicUtils.setStyle(stateLabel, "h1",
                Color.white);
        graphicUtils.setStyle(happyMessageLabel, "h4",
                Color.white);
        graphicUtils.setStyle(dateLabel, "h3",
                Color.white);
        graphicUtils.setStyle(principalButton, "h3",
                Color.white);
        graphicUtils.setStyle(lendingsButton, "h3",
                Color.white);
        graphicUtils.setStyle(returnsButton, "h3",
                Color.white);
        graphicUtils.setStyle(usersButton, "h3",
                Color.white);
        graphicUtils.setStyle(booksButton, "h3",
                Color.white);
        graphicUtils.setStyle(reportsButton, "h3",
                Color.white);
        titleSeparator.setForeground(Color.black);
        dateLabel.setText(graphicUtils.setDate());
    }

    /**
     * Inicializa los paneles (vistas).
     */
    private void initViews() {
        //inicializa los paneles y los almacena en una estructura key-data
        listViews = new HashMap<>();
        listViews.put("principalView", new Principal());
        listViews.put("lendingsView", new Lendings());
        listViews.put("returnsView", new Returns());
        listViews.put("usersView", new Users());
        listViews.put("booksView", new Books());
        listViews.put("reportsView", new Reports());

        //muestra el principal
        graphicUtils.showJPanel(listViews.get("principalView"),
                viewsPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        titleSeparator = new javax.swing.JSeparator();
        principalButton = new javax.swing.JButton();
        lendingsButton = new javax.swing.JButton();
        returnsButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        booksButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        IUModeButton = new javax.swing.JButton();
        statePanel = new javax.swing.JPanel();
        stateLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        happyMessageLabel = new javax.swing.JLabel();
        viewsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asistente de biblioteca");
        setMinimumSize(new java.awt.Dimension(960, 540));
        setName("formMain"); // NOI18N
        setSize(new java.awt.Dimension(854, 480));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(854, 480));
        background.setName(""); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(854, 480));

        menuPanel.setBackground(new java.awt.Color(204, 153, 0));
        menuPanel.setPreferredSize(new java.awt.Dimension(270, 640));

        titleLabel.setFont(new java.awt.Font("Papyrus", 1, 17)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        titleLabel.setText("Biblioteca Jaime Escalante");
        titleLabel.setToolTipText("");

        titleSeparator.setForeground(new java.awt.Color(0, 0, 0));
        titleSeparator.setPreferredSize(new java.awt.Dimension(50, 5));

        principalButton.setBackground(new java.awt.Color(216, 162, 0));
        principalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-outline.png"))); // NOI18N
        principalButton.setText("Principal");
        principalButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        principalButton.setBorderPainted(false);
        principalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        principalButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        principalButton.setIconTextGap(13);
        principalButton.setInheritsPopupMenu(true);
        principalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalButtonActionPerformed(evt);
            }
        });

        lendingsButton.setBackground(new java.awt.Color(216, 162, 0));
        lendingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar-multiple-check.png"))); // NOI18N
        lendingsButton.setText("Préstamos");
        lendingsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        lendingsButton.setBorderPainted(false);
        lendingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lendingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lendingsButton.setIconTextGap(13);
        lendingsButton.setInheritsPopupMenu(true);
        lendingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendingsButtonActionPerformed(evt);
            }
        });

        returnsButton.setBackground(new java.awt.Color(216, 162, 0));
        returnsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar-plus.png"))); // NOI18N
        returnsButton.setText("Devoluciones");
        returnsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        returnsButton.setBorderPainted(false);
        returnsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        returnsButton.setIconTextGap(13);
        returnsButton.setInheritsPopupMenu(true);
        returnsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnsButtonActionPerformed(evt);
            }
        });

        usersButton.setBackground(new java.awt.Color(216, 162, 0));
        usersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account-multiple.png"))); // NOI18N
        usersButton.setText("Usuarios");
        usersButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        usersButton.setBorderPainted(false);
        usersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        usersButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usersButton.setIconTextGap(13);
        usersButton.setInheritsPopupMenu(true);
        usersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersButtonActionPerformed(evt);
            }
        });

        booksButton.setBackground(new java.awt.Color(216, 162, 0));
        booksButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-open-page-variant.png"))); // NOI18N
        booksButton.setText("Libros");
        booksButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        booksButton.setBorderPainted(false);
        booksButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        booksButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        booksButton.setIconTextGap(13);
        booksButton.setInheritsPopupMenu(true);
        booksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksButtonActionPerformed(evt);
            }
        });

        reportsButton.setBackground(new java.awt.Color(216, 162, 0));
        reportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-chart.png"))); // NOI18N
        reportsButton.setText("Reportes");
        reportsButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        reportsButton.setBorderPainted(false);
        reportsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reportsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportsButton.setIconTextGap(13);
        reportsButton.setInheritsPopupMenu(true);
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });

        IUModeButton.setBackground(new java.awt.Color(204, 153, 0));
        IUModeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\OJavierHR\\Pictures\\Pokedex\\moon.png")); // NOI18N
        IUModeButton.setBorder(null);
        IUModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IUModeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lendingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(principalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(returnsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addComponent(booksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleSeparator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(IUModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lendingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(usersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(principalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(returnsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(booksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IUModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        statePanel.setBackground(new java.awt.Color(229, 172, 0));
        statePanel.setPreferredSize(new java.awt.Dimension(744, 150));

        stateLabel.setText("Main/Principal");

        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLabel.setText("Hoy es {dayname} {day} de {month} de {year}");

        happyMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        happyMessageLabel.setText("shhhh... silencio ♥");

        javax.swing.GroupLayout statePanelLayout = new javax.swing.GroupLayout(statePanel);
        statePanel.setLayout(statePanelLayout);
        statePanelLayout.setHorizontalGroup(
            statePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(stateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(statePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(happyMessageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        statePanelLayout.setVerticalGroup(
            statePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statePanelLayout.createSequentialGroup()
                .addGroup(statePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(happyMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        viewsPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addComponent(viewsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(statePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Evento que muestra la vista "principal".
     *
     * @param evt
     */
    private void principalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalButtonActionPerformed
        // TODO add your handling code here:
        stateLabel.setText(graphicUtils.setMainState("Principal"));
        showJPanel(listViews.get("principalView"));
    }//GEN-LAST:event_principalButtonActionPerformed
    /**
     * Evento que muestra la vista "prestamos".
     *
     * @param evt
     */
    private void lendingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendingsButtonActionPerformed
        // TODO add your handling code here:
        stateLabel.setText(graphicUtils.setMainState("Prestamos"));
        showJPanel(listViews.get("lendingsView"));
    }//GEN-LAST:event_lendingsButtonActionPerformed
    /**
     * Evento que muestra la vista "devoluciones".
     *
     * @param evt
     */
    private void returnsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnsButtonActionPerformed
        // TODO add your handling code here:
        stateLabel.setText(graphicUtils.setMainState("Devoluciones"));
        showJPanel(listViews.get("returnsView"));
    }//GEN-LAST:event_returnsButtonActionPerformed
    /**
     * Evento que muestra la vista "usuarios".
     *
     * @param evt
     */
    private void usersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButtonActionPerformed
        // TODO add your handling code here:
        stateLabel.setText(graphicUtils.setMainState("Usuarios"));
        showJPanel(listViews.get("usersView"));
    }//GEN-LAST:event_usersButtonActionPerformed
    /**
     * Evento que muestra la vista "libros".
     *
     * @param evt
     */
    private void booksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksButtonActionPerformed
        // TODO add your handling code here:
        stateLabel.setText(graphicUtils.setMainState("Libros"));
        showJPanel(listViews.get("booksView"));
    }//GEN-LAST:event_booksButtonActionPerformed
    /**
     * Evento que muestra la vista "reportes".
     *
     * @param evt
     */
    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        // TODO add your handling code here:
        stateLabel.setText(graphicUtils.setMainState("Reportes"));
        showJPanel(listViews.get("reportsView"));
    }//GEN-LAST:event_reportsButtonActionPerformed
    /**
     * Procedimiento que selecciona el modo de visualizacion en funcion del
     * estado de la bandera "modeDark".
     *
     * @param evt
     */
    private void IUModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IUModeButtonActionPerformed
        // TODO add your handling code here:
        if (FormMain.modeDark) {
            FlatArcDarkOrangeIJTheme.setup();
            java.awt.EventQueue.invokeLater(() -> {
                FormMain.modeDark = false;
                new FormMain().setVisible(true);
                this.dispose();
            });
        } else {
            FlatArcOrangeIJTheme.setup();
            java.awt.EventQueue.invokeLater(() -> {
                FormMain.modeDark = true;
                new FormMain().setVisible(true);
                this.dispose();
            });
        }
    }//GEN-LAST:event_IUModeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IUModeButton;
    private javax.swing.JPanel background;
    private javax.swing.JButton booksButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel happyMessageLabel;
    private javax.swing.JButton lendingsButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton principalButton;
    private javax.swing.JButton reportsButton;
    private javax.swing.JButton returnsButton;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JPanel statePanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JSeparator titleSeparator;
    private javax.swing.JButton usersButton;
    private static javax.swing.JPanel viewsPanel;
    // End of variables declaration//GEN-END:variables
    /**
     * Operacion que muestra un jPanel en el panel "viewsPanel" del interfaz de
     * usuario.
     *
     * @param panelShow
     */
    public static void showJPanel(JPanel panelShow) {
        graphicUtils.showJPanel(panelShow, viewsPanel);
    }
}
